[project]
name = "iscc-sci"
version = "0.2.0"
description = "ISCC - Semantic Code Image"
authors = [{ name = "Titusz", email = "tp@py7.de" }]
requires-python = ">=3.11"
readme = "README.md"
license = "Apache-2.0"
keywords = [
    "iscc",
    "semantic",
    "media",
    "hash",
    "similarity",
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: BSD License",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Multimedia",
    "Topic :: Multimedia :: Graphics",
    "Topic :: Scientific/Engineering :: Image Recognition",
    "Topic :: Scientific/Engineering :: Information Analysis",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
dependencies = [
    "pillow",
    "onnxruntime",
    "loguru",
    "blake3",
    "platformdirs",
    "pydantic-settings",
]

[project.optional-dependencies]
gpu = ["onnxruntime-gpu"]

[project.urls]
Homepage = "https://iscc.codes"
Repository = "https://github.com/iscc/iscc-sci"

[project.scripts]
iscc-sci = "iscc_sci.cli:main"

[dependency-groups]
test = [
    "pytest",
    "coverage",
    "pytest-cov",
    "iscc-samples",
]
dev = [
    "poethepoet",
    "ruff",
]
docs = [
    "mdformat-gfm",
    "mdformat-gfm-alerts",
    "mdformat-frontmatter",
]

[tool.uv]
default-groups = "all"

[tool.uv.build-backend]
module-root = ""

[build-system]
requires = ["uv_build"]
build-backend = "uv_build"

[tool.ruff]
line-length = 100

[tool.ruff.format]
line-ending = "lf"

[tool.poe.tasks]
format-code = { cmd = "ruff format", help = "Code style formating with ruff" }
format-md = { cmd = "mdformat --wrap 100 --end-of-line lf README.md", help = "Markdown formating with mdformat" }
test = { cmd = "pytest --cov=iscc_sci --cov-fail-under=100", help = "Run tests with coverage" }
all = ["format-code", "format-md", "test"]
